### ISSUE TITLE
Caret in entry widget should be updated before the onchange event handler is called

### ISSUE THREAD

**Issue by sinfricia** [jtackaberry/rtk#19]
Then the caret position could be changed in the onchange function. This is useful if the user types a character that is 'not allowed' in that entry and is therefore replaced by an empty string in the onchange function. Currently the carret just advances when this happens and there seems to be no way to easily control it.

Maybe I'm just incompetent though :)

**Comment by jtackaberry** [comment]
Hey @sinfricia I'm very sorry for the slow reply.

I do agree something isn't working quite right here with respect to the caret position at the time the `onchange()` handler is called.  It *should* indicate the current position after the change has been made, but that's not always working properly.  I'll work on a fix for this.

That said, the onchange() handler probably isn't the best place to intercept and prevent user-driven keyboard input.  I'd hook `onkeypress()` instead, where you can return false to reject a character.  This example will prevent the character `x` from being allowed into the entry:

```lua
local e = rtk.Entry()
e.onkeypress = function(self, event)
    if event.char == 'x' then
        return false
    end
end
```

**Comment by jtackaberry** [comment]
Fix to ensure caret is updated before onchange() is committed to master, will land in the next release.
